[project]
name = "cryptography"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ElenTerteryan", email = "166726248+ElenTerteryan@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
cryptography = "cryptography:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
